# auto: true
markdown: kramdown
highlighter: rouge
paginate: 8
permalink: /:title
encoding: UTF-8
gems: [jekyll-paginate]
 
title: godchin1990
url: http://Godchin1990.github.io
feed: /atom.xml
author_info: <a href="http://Godchin1990.github.io/">godchin</a>

myblog:
  gavatar: images/2.jpg
  gpname: godchin
  linkedin: http://380580655.qzone.qq.com/?t=0.21065967064350843
  github: http://Godchin1990.github.io
  email: mailto:godchin1990@@gmail.com
  coverimgs: []
  postbgimg: []

categories: [python, books]
