# auto: true
markdown: kramdown
highlighter: rouge
paginate: 8
permalink: /:title
encoding: UTF-8
gems: [jekyll-paginate]
 
title: godchin1990
url: http://Godchin1990.github.io
feed: /atom.xml
author_info: <a href="http://Godchin1990.github.io/">godchin</a>

myblog:
  gavatar: images/2.jpg
  gpname: godchin
  linkedin: http://my.csdn.net/gongdaoquan
  github: https://github.com/Godchin1990
  email: mailto:godchin1990@gmail.com
  coverimgs: []
  postbgimg: []

categories: [python, books]
